In [6]:
import numpy as np

In [7]:
data = np.array([
    [1, 100, 10],
    [2, 300, 15],
    [4, 200, 20],
    [2, 600, 10],
    [5, 100, 30]
])
# first column = feature A, second column = B, ... C

In [8]:
x = np.array([[4, 500, 40]])
m = np.mean(data, axis=0)
print("Mean: ", m)

Mean:  [  2.8 260.   17. ]


In [10]:
print("The difference (x-m): ", x-m)

The difference (x-m):  [[  1.2 240.   23. ]]


In [11]:
data = np.transpose(data)
covM = np.cov(data, bias = False)
invCovM = np.linalg.inv(covM)

In [12]:
print("Covariance matrix of data: \n", covM)
print("Inverse covariance matrix of data: \n", invCovM)

Covariance matrix of data: 
 [[ 2.7e+00 -1.1e+02  1.3e+01]
 [-1.1e+02  4.3e+04 -9.0e+02]
 [ 1.3e+01 -9.0e+02  7.0e+01]]
Inv covariance matrix of data: 
 [[ 5.50e+00 -1.00e-02 -1.15e+00]
 [-1.00e-02  5.00e-05  2.50e-03]
 [-1.15e+00  2.50e-03  2.60e-01]]


In [17]:
# calculate the distance (x-m)^T*cov^-1*(x-m)
MD2 = np.dot(np.dot((x-m), invCovM), np.transpose(x-m))
print(MD2)
# be careful that you switch the order! 
# np.dot(a,b) calculates a^T*b, so a^T^T*b

[[106.7]]


In [21]:
MD = np.sqrt(MD2)
print("The Mahalanobis distance: ", np.reshape(MD,-1))

The Mahalanobis distance:  [10.32956921]


<b>Exercise: </b><br/>
Calculate the mahalanobis distance between the following two vectors <br/>
<table>
<thead>
  <tr>
    <th>x</th>
    <th>y</th>
    <th>z</th>
  </tr>

 <tr>
    <td>Height</td>
    <td>Score</td>
    <td>Age</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td>64.0</td>
    <td>580.0</td>
    <td>29.0</td>
  </tr>
  <tr>
    <td>66.0</td>
    <td>570.0</td>
    <td>33.0</td>
  </tr>
  <tr>
    <td>68.0</td>
    <td>590.0</td>
    <td>37.0</td>
  </tr>
  <tr>
    <td>69.0</td>
    <td>660.0</td>
    <td>46.0</td>
  </tr>
  <tr>
    <td>73.0</td>
    <td>600.0</td>
    <td>55.0</td>
  </tr>
</tbody>
</table>
and
<table>
    <tr>
        <td>m=68.0</td>
        <td>600.0</td>
        <td>40.0</td>
    </tr>    
</table>

    

In [22]:
data2 = np.array([
    [64, 580, 29],
    [66, 570, 33],
    [68, 590, 37],
    [69, 660, 46],
    [73, 600, 55]
])

In [23]:
x2 = np.array([[68, 600, 40]])
data2Mean = np.mean(data2, axis=0)

In [24]:
data2 = np.transpose(data2)
covM2 = np.cov(data2, bias = False)
invCovM2 = np.linalg.inv(covM2)

In [29]:
print(covM2)
print(invCovM2)

[[  11.5    50.     34.75]
 [  50.   1250.    205.  ]
 [  34.75  205.    110.  ]]
[[ 3.68851865e+00  6.27308946e-02 -1.28214415e+00]
 [ 6.27308946e-02  2.21900278e-03 -2.39526742e-02]
 [-1.28214415e+00 -2.39526742e-02  4.58770977e-01]]


In [30]:
x2 - data2Mean

array([[0., 0., 0.]])

In [27]:
MD2 = np.dot(np.dot((x2-data2Mean), invCovM2), np.transpose(x2-data2Mean))
MD = np.sqrt(MD2)
print("The mahalanobis distance is: ", MD2)

The mahalanobis distance is:  [[0.]]


In [33]:
x3 = np.array([[66, 640, 44]])
MD2 = np.dot(np.dot((x3-data2Mean), invCovM2), np.transpose(x3-data2Mean))
MD = np.sqrt(MD2)
print("The mahalanobis distance is: ", MD)

The mahalanobis distance is:  [[5.33454049]]
